[build-system]
requires = ["setuptools>=75.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ann-assistant"
version = "0.0.13"
description = "A modular desktop AI Assistant."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "PySide6==6.8.0.2",
    "scapy==2.6.1",
]

[project.scripts]
ann = "ann.app:main"

[tool.setuptools]
package-dir = {"" = "Ann_core/src"}

[tool.setuptools.packages.find]
where = ["Ann_core/src"]
